// ============================================================
// PDF Export Service — generates downloadable PDFs with test
// questions and optional answer key using jsPDF.
// ============================================================

import { jsPDF } from 'jspdf';
import type { Test, Question } from './types';

// --- Constants ---

const MARGIN = 20;
const PAGE_WIDTH = 210; // A4 width in mm
const PAGE_HEIGHT = 297; // A4 height in mm
const USABLE_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_Y = 285;

// Obsidian Studio dark-adapted colours (subdued for white PDF background)
const COLOUR = {
  text: [30, 30, 50] as [number, number, number],        // dark navy
  title: [15, 15, 35] as [number, number, number],       // nearly black
  subtitle: [80, 80, 100] as [number, number, number],   // medium grey
  accent: [100, 60, 200] as [number, number, number],    // purple accent
  correct: [45, 110, 80] as [number, number, number],    // green
  footer: [140, 140, 160] as [number, number, number],   // light grey
  option: [50, 50, 70] as [number, number, number],      // dark grey for options
};

function rgb(c: [number, number, number]): [number, number, number] {
  return c;
}

// --- Helpers ---

/** Format a date string to a human-readable form, or return today. */
function formatDate(dateStr?: string): string {
  if (!dateStr) return new Date().toLocaleDateString('en-GB');
  try {
    return new Date(dateStr).toLocaleDateString('en-GB');
  } catch {
    return dateStr;
  }
}

/** Difficulty badge emoji/icon label. */
function difficultyLabel(difficulty: string): string {
  switch (difficulty.toLowerCase()) {
    case 'easy':   return '🟢 Easy';
    case 'medium': return '🟡 Medium';
    case 'hard':   return '🔴 Hard';
    default:       return difficulty;
  }
}

/** Check if y is near the bottom of the page; if so, add a new page. */
function ensureSpace(doc: jsPDF, y: number, needed: number): { y: number } {
  if (y + needed > FOOTER_Y - 5) {
    doc.addPage();
    return { y: MARGIN };
  }
  return { y };
}

/** Draw the consistent footer on the current page. */
function drawFooter(doc: jsPDF) {
  doc.setFontSize(8);
  doc.setTextColor(...rgb(COLOUR.footer));
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Pressey AI Test Generator', MARGIN, FOOTER_Y);
}

/** Draw a horizontal rule at y. */
function hr(doc: jsPDF, y: number): number {
  doc.setDrawColor(...rgb(COLOUR.subtitle));
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  return y + 4;
}

// --- Main export function ---

export async function exportTestToPdf(
  test: Test,
  includeAnswerKey: boolean,
): Promise<Uint8Array> {
  const doc = new jsPDF();
  let y = MARGIN;

  // ==========================================================
  // 1. TITLE PAGE
  // ==========================================================

  // Title — large, bold
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(...rgb(COLOUR.title));
  const titleLines = doc.splitTextToSize(test.title, USABLE_WIDTH);
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 12 + 8;

  // Horizontal rule
  y = hr(doc, y);

  // Topic
  if (test.topic) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(...rgb(COLOUR.subtitle));
    doc.text(`Topic: ${test.topic}`, MARGIN, y);
    y += 10;
  }

  // Difficulty badge
  doc.setFontSize(14);
  doc.setTextColor(...rgb(COLOUR.accent));
  doc.text(`Difficulty: ${difficultyLabel(test.difficulty)}`, MARGIN, y);
  y += 10;

  // Question count
  doc.setTextColor(...rgb(COLOUR.subtitle));
  doc.text(`Questions: ${test.questions.length}`, MARGIN, y);
  y += 8;

  // MCQ / text breakdown
  const mcqCount = test.questions.filter((q) => q.type === 'mcq').length;
  const textCount = test.questions.filter((q) => q.type === 'text').length;
  doc.text(`Multiple Choice: ${mcqCount}  |  Written: ${textCount}`, MARGIN, y);
  y += 10;

  // Generation date
  doc.setFontSize(11);
  doc.setTextColor(...rgb(COLOUR.subtitle));
  doc.text(`Generated: ${formatDate(test.createdAt)}`, MARGIN, y);
  y += 14;

  // Horizontal rule
  y = hr(doc, y);

  // Brief instructions
  doc.setFontSize(10);
  doc.setTextColor(...rgb(COLOUR.text));
  doc.text('Read each question carefully. Circle the best answer for multiple-choice questions.', MARGIN, y);
  y += 6;
  doc.text('Write your answer in the space provided for written questions.', MARGIN, y);

  // Footer on title page
  drawFooter(doc);

  // ==========================================================
  // 2. QUESTION PAGES
  // ==========================================================

  doc.addPage();
  y = MARGIN;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...rgb(COLOUR.title));
  doc.text('Questions', MARGIN, y);
  y += 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...rgb(COLOUR.text));

  for (let i = 0; i < test.questions.length; i++) {
    const q = test.questions[i];
    const qNum = i + 1;

    // Check space — need at least 30mm for a minimal question
    const sp = ensureSpace(doc, y, 30);
    if (sp.y !== y) { y = sp.y; drawFooter(doc); }

    const questionLabel = `${qNum}. [${q.type.toUpperCase()}] ${q.text}`;
    const wrapped = doc.splitTextToSize(questionLabel, USABLE_WIDTH);
    doc.setFont('helvetica', 'bold');
    doc.text(wrapped, MARGIN, y);
    y += wrapped.length * 6 + 4;

    if (q.type === 'mcq' && q.options && q.options.length > 0) {
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...rgb(COLOUR.option));
      const labels = ['A', 'B', 'C', 'D'];
      for (let j = 0; j < q.options.length; j++) {
        const opt = q.options[j];
        const label = labels[j] || `${j + 1}`;
        const optText = `${label}) ${opt}`;
        const optWrapped = doc.splitTextToSize(optText, USABLE_WIDTH - 6);
        // Indent options slightly
        doc.text(optWrapped, MARGIN + 6, y);
        y += optWrapped.length * 5.5 + 2;
      }
    } else if (q.type === 'text') {
      // Blank lines for written answer
      doc.setDrawColor(...rgb(COLOUR.subtitle));
      doc.setLineWidth(0.2);
      for (let k = 0; k < 4; k++) {
        doc.line(MARGIN, y + 2, PAGE_WIDTH - MARGIN, y + 2);
        y += 8;
      }
    }

    y += 6; // spacing after each question

    // Footer on every page
    drawFooter(doc);
  }

  // ==========================================================
  // 3. ANSWER KEY (optional)
  // ==========================================================

  if (includeAnswerKey && test.questions.length > 0) {
    doc.addPage();
    y = MARGIN;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(...rgb(COLOUR.title));
    doc.text('Answer Key', MARGIN, y);
    y += 12;

    for (let i = 0; i < test.questions.length; i++) {
      const q = test.questions[i];
      const qNum = i + 1;

      // Ensure space
      const sp = ensureSpace(doc, y, 25);
      if (sp.y !== y) { y = sp.y; drawFooter(doc); }

      // Question text (abbreviated)
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...rgb(COLOUR.text));
      const qText = `${qNum}. ${q.text}`;
      const qWrapped = doc.splitTextToSize(qText, USABLE_WIDTH);
      doc.text(qWrapped, MARGIN, y);
      y += qWrapped.length * 5 + 2;

      // Correct answer in green
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...rgb(COLOUR.correct));
      doc.text(`Answer: ${q.correctAnswer}`, MARGIN + 4, y);
      y += 6;

      // Explanation in smaller text
      if (q.explanation) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...rgb(COLOUR.subtitle));
        const expWrapped = doc.splitTextToSize(q.explanation, USABLE_WIDTH - 4);
        doc.text(expWrapped, MARGIN + 4, y);
        y += expWrapped.length * 4.5 + 4;
      }

      y += 4;

      // Footer
      drawFooter(doc);
    }
  }

  // ==========================================================
  // 4. ADD PAGE NUMBERS TO EVERY PAGE
  // ==========================================================

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...rgb(COLOUR.footer));
    doc.setFont('helvetica', 'italic');
    doc.text(`Page ${i} of ${totalPages}`, PAGE_WIDTH - MARGIN, FOOTER_Y, { align: 'right' });
  }

  // Return as Uint8Array (suitable for Tauri save dialog)
  const buffer = doc.output('arraybuffer');
  return new Uint8Array(buffer);
}
